- name: Join Swarm Cluster as a Manager
  command: sudo docker swarm join --token {{ token }} {{ manager }}:2377
  register: manager

- name: Show Results
  debug: var=manager.stdout

- name: Show Errors
  debug: var=manager.stderr